const photos=[['荒野边缘','https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=82'],['岩层与风','https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1400&q=82'],['城市游离','https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1400&q=82']];
export default function Home(){return <main>
<nav className="nav"><a className="wordmark" href="#top">ZHOUYAWEI<span>/ VISUAL ARCHIVE</span></a><div className="nav-links"><a href="#profile">简介</a><a href="#graphic">平面</a><a href="#motion">视频</a><a href="#contact">合作</a></div></nav>
<header className="hero" id="top"><div className="grain"/><div className="folio">PORTFOLIO<br/>MMXXVI</div><div className="hero-copy"><p>PHOTOGRAPHY · FILM · ART DIRECTION</p><h1>ZHOU<br/><i>YAWEI</i></h1><div className="hero-note"><span>01</span><p>从自然的表皮与城市的缝隙中，<br/>拾取时间留下的纹理。</p></div></div><a className="scroll" href="#profile">SCROLL TO READ ↓</a></header>
<section className="profile paper" id="profile"><p className="label">01 / PROFILE</p><div><h2>个人简介</h2><p className="lead">我是 Zhou Yawei，一名关注自然、身体与场所关系的独立视觉创作者。以摄影和动态影像为主要媒介，在真实记录与先锋表达之间建立叙事。</p><div className="profile-meta"><span>BASED IN CHINA</span><span>AVAILABLE WORLDWIDE</span><span>EST. 2024</span></div></div></section>
<section className="gallery" id="graphic"><header className="section-head"><p>02 / PHOTOGRAPHY</p><h2>平面作品</h2><span>SELECTED 03</span></header><div className="photo-grid">{photos.map((p,i)=><article className={`photo p${i+1}`} key={p[0]}><div className="image-wrap"><img src={p[1]} alt={p[0]}/><span>0{i+1}</span></div><h3>{p[0]}</h3><p>PERSONAL SERIES / 2026</p></article>)}</div></section>
<section className="motion" id="motion"><div className="motion-image"><img src="https://images.unsplash.com/photo-1486911278844-a81c5267e227?auto=format&fit=crop&w=2000&q=85" alt="视频作品封面"/><span className="play">▶</span></div><div className="motion-copy"><p className="label">03 / MOTION</p><h2>视频<br/>作品</h2><p>品牌短片、户外纪录、人物故事与实验影像。</p><a href="#contact">VIEW FILM INDEX ↗</a></div></section>
<section className="partners paper"><p className="label">04 / COLLABORATION</p><div><h2>合作品牌</h2><p className="subcopy">横跨时装、配饰、珠宝、腕表与生活方式领域的视觉创作与项目经验。</p><figure className="brand-board"><img src="/brands.png" alt="BOSS、DIESEL、TUMI、MCM、BALLY、GUCCI、New Balance、PANDORA、Clarks、Kipling等合作品牌"/><figcaption>SELECTED CLIENTS / BRAND COLLABORATIONS</figcaption></figure></div></section>
<section className="projects"><header className="section-head"><p>05 / PROJECTS</p><h2>参与项目</h2><span>ARCHIVE</span></header>{[['2026','高山影像计划','DOCUMENTARY / PHOTOGRAPHY'],['2025','城市边界','EDITORIAL / VISUAL STORY'],['2024','风的档案','PERSONAL / MOTION']].map(x=><div className="project-row" key={x[1]}><div><span>{x[0]}</span><h3>{x[1]}</h3></div><p>{x[2]}</p></div>)}</section>
<footer id="contact"><p className="label">06 / CONTACT</p><div className="contact-title"><p>LET&apos;S MAKE<br/>SOMETHING REAL.</p><h2>一起合作</h2></div><div className="contact-links"><a href="mailto:hello@zhouyawei.com">HELLO@ZHOUYAWEI.COM ↗</a><span>WECHAT / 待填写</span><span>RED / 待填写</span></div><div className="footnote"><b>ZHOUYAWEI°</b><span>© 2026 ALL RIGHTS RESERVED</span></div></footer>
</main>}
